# Generated by Django 3.0.7 on 2020-06-25 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='customer',
            name='address_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customer',
            name='code_phone',
            field=models.SmallIntegerField(choices=[(8029, '(029)'), (8033, '(033)'), (8044, '(044)'), (8017, '(017)')], default=8029, verbose_name='Код номера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='customer',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(default=1234567, help_text='7 цифр', verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
