# Generated by Django 3.0.7 on 2020-06-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('customers', '0002_auto_20200625_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='group',
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='Группа'),
        ),
    ]
