# Generated by Django 3.0.7 on 2020-07-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('customers', '0004_auto_20200627_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='Группа'),
        ),
    ]
