# Generated by Django 3.0.7 on 2020-06-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200621_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code_phone',
            field=models.SmallIntegerField(choices=[(8029, '(029)'), (8033, '(033)'), (8044, '(044)')], default=8029, verbose_name='Код номера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(help_text='7 цифр', verbose_name='Телефон'),
        ),
    ]
