# Generated by Django 3.0.7 on 2020-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200621_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code_phone',
            field=models.SmallIntegerField(choices=[(8029, '(029)'), (8033, '(033)'), (8044, '(044)'), (8017, '(017)')], verbose_name='Код номера'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
