# Generated by Django 3.0.6 on 2020-06-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.Genre', verbose_name='Жанр книги')),
            ],
        ),
    ]
