# Generated by Django 3.0.7 on 2020-06-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20200615_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название жанра'),
        ),
    ]
