# Generated by Django 3.0.7 on 2020-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20200701_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_genre', models.FileField(upload_to='files', verbose_name='Каталог жанров')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Каталог жанров',
                'verbose_name_plural': 'Каталоги жанров',
            },
        ),
    ]
