# Generated by Django 3.0.7 on 2020-06-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20200627_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelTable(
            name='genre',
            table=None,
        ),
    ]
