# Generated by Django 3.0.7 on 2020-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0005_import_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Поле может быть пустым', null=True, verbose_name='Описание жанра'),
        ),
    ]
