# Generated by Django 3.0.7 on 2020-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200704_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена'),
        ),
    ]
