# Generated by Django 3.0.7 on 2020-07-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200704_2113'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_auto_20200704_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('in process', 'В обработке'), ('delivery', 'доставка'), ('cancel', 'отменен'), ('close', 'Закрыт')], default='open', max_length=100, verbose_name='Код номера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_in_order', to='cart.Cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
