# Generated by Django 3.0.7 on 2020-07-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200704_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('in process', 'В обработке'), ('delivery', 'Доставка'), ('cancel', 'Отменен'), ('close', 'Закрыт')], default='open', max_length=100, verbose_name='Код номера'),
        ),
    ]
