# Generated by Django 3.0.7 on 2020-07-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200707_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Открыт', 'Открыт'), ('В обработке', 'В обработке'), ('Доставка', 'Доставка'), ('Отменен', 'Отменен'), ('Закрыт', 'Закрыт')], default='Открыт', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
