# Generated by Django 3.0.7 on 2020-07-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200704_2113'),
        ('order', '0014_auto_20200707_2059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('cart', 'price')},
        ),
    ]
