# Generated by Django 3.0.7 on 2020-07-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200704_2113'),
        ('order', '0016_auto_20200707_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('cart', 'price')},
        ),
    ]
