# Generated by Django 3.0.7 on 2020-07-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200704_2113'),
        ('order', '0019_auto_20200713_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart_in_order', to='cart.Cart', verbose_name='Корзина'),
        ),
    ]
