# Generated by Django 3.0.7 on 2020-07-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20200714_1307'),
        ('order', '0021_auto_20200714_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart_in_order', to='cart.Cart', verbose_name='Корзина'),
        ),
    ]
