# Generated by Django 3.0.7 on 2020-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_comment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='order.Comment_Order', verbose_name='Комментарии к заказу'),
        ),
    ]
