# Generated by Django 3.0.7 on 2020-07-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20200716_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
