# Generated by Django 3.0.7 on 2020-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20200715_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.ManyToManyField(blank=True, to='order.Comment_Order', verbose_name='Комментарии к заказу'),
        ),
    ]
