# Generated by Django 3.0.7 on 2020-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200715_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comments', to='order.Comment_Order', verbose_name='Комментарии к заказу'),
        ),
    ]
