# Generated by Django 3.0.7 on 2020-07-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20200715_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Заказ'),
        ),
    ]
