# Generated by Django 3.0.7 on 2020-07-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20200715_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_order',
            name='comment',
            field=models.TextField(max_length=100, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='order.Order', verbose_name='Заказ'),
        ),
    ]
