# Generated by Django 3.0.7 on 2020-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_auto_20200715_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_order',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
    ]
