# Generated by Django 3.0.7 on 2020-07-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20200715_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_order',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment_order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='order.Comment_Order', verbose_name='Комментарии'),
        ),
    ]
