# Generated by Django 3.0.7 on 2020-07-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20200715_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_order',
            old_name='text',
            new_name='comment',
        ),
    ]
