# Generated by Django 3.0.7 on 2020-07-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20200715_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_order',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='order.Comment_Order', verbose_name='Комментарии'),
        ),
    ]
