# Generated by Django 3.0.7 on 2020-07-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20200715_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment_order',
            unique_together={('order', 'created')},
        ),
    ]
