# Generated by Django 3.0.7 on 2020-07-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20200715_2333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment_order',
            unique_together=set(),
        ),
    ]
