# Generated by Django 3.0.7 on 2020-06-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0003_auto_20200627_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfo',
            options={'ordering': ['name'], 'verbose_name': 'О магазине', 'verbose_name_plural': 'О магазине'},
        ),
    ]
