# Generated by Django 3.0.7 on 2020-07-21 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0007_auto_20200717_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, verbose_name='USD')),
                ('eur', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, verbose_name='EUR')),
                ('rub', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, verbose_name='RUB')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Каталог курсов валют',
                'verbose_name_plural': 'Каталоги курсов валют',
            },
        ),
    ]
