# Generated by Django 3.0.7 on 2020-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0011_auto_20200721_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_currency',
            name='created',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Создано'),
        ),
    ]
