# Generated by Django 3.0.7 on 2020-06-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200615_1240'),
        ('bookapp', '0004_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='author.Author', verbose_name='Автор'),
        ),
    ]
