# Generated by Django 3.0.7 on 2020-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='static/book/10912445_0.jpg', upload_to='static/book'),
        ),
    ]
