# Generated by Django 3.0.7 on 2020-06-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_book_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
    ]
