# Generated by Django 3.0.7 on 2020-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20200615_1240'),
        ('bookapp', '0009_book_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='genre.Genre', verbose_name='Жанр книги'),
        ),
    ]
