# Generated by Django 3.0.7 on 2020-06-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_auto_20200615_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2019, max_length=4, verbose_name='Год издания'),
            preserve_default=False,
        ),
    ]
