# Generated by Django 3.0.7 on 2020-06-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Кол-во страниц'),
            preserve_default=False,
        ),
    ]
