# Generated by Django 3.0.7 on 2020-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_book_bookbinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookbinding',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Переплет'),
        ),
    ]
