# Generated by Django 3.0.7 on 2020-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0015_auto_20200615_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Формат'),
        ),
    ]
