# Generated by Django 3.0.7 on 2020-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_book_book_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='ISBN'),
        ),
    ]
