# Generated by Django 3.0.7 on 2020-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0017_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Указывается в граммах', max_length=100, null=True, verbose_name='Вес (гр)'),
        ),
    ]
