# Generated by Django 3.0.7 on 2020-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0019_auto_20200615_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.CharField(default='0+', max_length=100, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Указывается в граммах', null=True, verbose_name='Вес (гр)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год издания'),
        ),
    ]
