# Generated by Django 3.0.7 on 2020-06-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0020_auto_20200615_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Издательство'),
        ),
    ]
