# Generated by Django 3.0.7 on 2020-06-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0022_auto_20200615_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='В наличии'),
            preserve_default=False,
        ),
    ]
