# Generated by Django 3.0.7 on 2020-06-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0023_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, max_length=2),
        ),
    ]
