# Generated by Django 3.0.7 on 2020-06-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0024_book_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, max_length=2, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
