# Generated by Django 3.0.7 on 2020-06-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0025_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Рейтинг'),
        ),
    ]
