# Generated by Django 3.0.7 on 2020-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0027_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='static/books/incognito.png', upload_to='books'),
        ),
    ]
