# Generated by Django 3.0.7 on 2020-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0029_auto_20200616_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='static/books/incognito.png', upload_to='books', verbose_name='Изображение'),
        ),
    ]
