# Generated by Django 3.0.7 on 2020-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0031_auto_20200616_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='books', verbose_name='Изображение'),
        ),
    ]
