# Generated by Django 3.0.7 on 2020-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0033_auto_20200616_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Аннотация'),
        ),
    ]
