# Generated by Django 3.0.7 on 2020-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0034_book_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(help_text='Поле может быть пустым', verbose_name='Аннотация'),
        ),
    ]
