# Generated by Django 3.0.7 on 2020-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0035_auto_20200617_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='от 0 до 9', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ГГГГ', null=True, verbose_name='Год издания'),
        ),
    ]
