# Generated by Django 3.0.7 on 2020-06-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0038_remove_book_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('view_active', 'Can view active books')]},
        ),
    ]
