# Generated by Django 3.0.7 on 2020-06-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0039_auto_20200619_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('view_active', 'Can view active books'),)},
        ),
    ]
