# Generated by Django 3.0.7 on 2020-06-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0041_auto_20200620_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('active', 'Can view active books')]},
        ),
    ]
