# Generated by Django 3.0.7 on 2020-06-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0042_auto_20200620_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('view_active_book', 'Can view active books')]},
        ),
    ]
