# Generated by Django 3.0.7 on 2020-06-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0043_auto_20200620_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('view_active_book', 'Can view active books'), ('view_admin_db', 'Can view admin db')]},
        ),
    ]
