# Generated by Django 3.0.7 on 2020-06-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0045_auto_20200627_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('view_active_book', 'Can view active books'), ('view_admin_db', 'Can view admin db')], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
