# Generated by Django 3.0.7 on 2020-07-11 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0015_auto_20200627_1952'),
        ('genre', '0004_auto_20200701_0030'),
        ('bookapp', '0048_auto_20200710_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='age_limit',
            field=models.CharField(blank=True, default='0+', max_length=100, null=True, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='author.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='genre.Genre', verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='books', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='от 0 до 10', null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Аннотация'),
        ),
    ]
