# Generated by Django 3.0.7 on 2020-07-11 19:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0016_auto_20200711_2134'),
        ('genre', '0004_auto_20200701_0030'),
        ('bookapp', '0050_auto_20200711_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='age_limit',
            field=models.CharField(default='0+', max_length=100, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='author.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='genre.Genre', verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='books', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='от 0 до 10', verbose_name='Рейтинг'),
        ),
    ]
