# Generated by Django 3.0.7 on 2020-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0051_auto_20200711_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='В наличии'),
        ),
    ]
