# Generated by Django 3.0.7 on 2020-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0018_auto_20200712_2201'),
        ('bookapp', '0052_auto_20200711_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='author.Author', verbose_name='Автор'),
        ),
    ]
