# Generated by Django 3.0.7 on 2020-07-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0053_auto_20200713_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['rating'], 'permissions': [('view_active_book', 'Can view active books'), ('view_admin_db', 'Can view admin db')], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
