# Generated by Django 3.0.7 on 2020-07-16 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0054_auto_20200716_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
