# Generated by Django 3.0.7 on 2020-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0055_import_book_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='books/incognito.png', upload_to='books', verbose_name='Изображение'),
        ),
    ]
