# Generated by Django 3.0.7 on 2020-07-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('genre', '0005_import_genre'),
        ('bookapp', '0056_auto_20200717_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genrebooks', to='genre.Genre', verbose_name='Жанр книги'),
        ),
        migrations.CreateModel(
            name='Comment_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.Book', verbose_name='Книга')),
                ('role_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='Группа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к книге',
                'verbose_name_plural': 'Комментарии к книгам',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comments', to='bookapp.Comment_Book', verbose_name='Комментарии'),
        ),
    ]
