# Generated by Django 3.0.7 on 2020-07-19 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0057_auto_20200719_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment_book',
            unique_together={('user', 'book')},
        ),
    ]
