# Generated by Django 3.0.7 on 2020-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0059_auto_20200719_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_book',
            name='rating',
            field=models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', max_length=100, verbose_name='Оценка'),
        ),
    ]
