# Generated by Django 3.0.7 on 2020-07-21 11:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0060_comment_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.00'), help_text='от 0 до 10', max_digits=6, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='comment_book',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=100, verbose_name='Оценка'),
        ),
    ]
