# Generated by Django 3.0.7 on 2020-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0061_auto_20200721_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pk'], 'permissions': [('view_active_book', 'Can view active books'), ('view_admin_db', 'Can view admin db')], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='comment_book',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='10', max_length=100, verbose_name='Оценка'),
        ),
    ]
