# Generated by Django 3.0.7 on 2020-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0064_auto_20200721_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_book',
            name='rating',
            field=models.CharField(choices=[('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('0', '0')], default='10', max_length=100, verbose_name='Оценка'),
        ),
    ]
