# Generated by Django 3.0.7 on 2020-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0066_auto_20200721_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='от 0 до 10', max_digits=6, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='comment_book',
            name='rating',
            field=models.CharField(choices=[('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=100, null=True, verbose_name='Оценка'),
        ),
    ]
