# Generated by Django 3.0.7 on 2020-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0072_auto_20200723_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='от 0 до 5', max_digits=6, null=True, verbose_name='Рейтинг'),
        ),
    ]
