# Generated by Django 3.0.7 on 2020-06-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktocart',
            name='price',
        ),
    ]
