# Generated by Django 3.0.7 on 2020-06-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200630_2239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktocart',
            unique_together=set(),
        ),
    ]
