# Generated by Django 3.0.7 on 2020-06-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0046_auto_20200627_1952'),
        ('cart', '0007_auto_20200630_2243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktocart',
            unique_together={('cart', 'book')},
        ),
    ]
