# Generated by Django 3.0.7 on 2020-07-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20200714_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktocart',
            options={'ordering': ['cart'], 'verbose_name': 'Состав корзины', 'verbose_name_plural': 'Состав корзин'},
        ),
    ]
