# Generated by Django 3.0.7 on 2020-07-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20200719_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktocart',
            unique_together=set(),
        ),
    ]
