# Generated by Django 3.0.7 on 2020-07-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0072_auto_20200723_1447'),
        ('cart', '0016_auto_20200723_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktocart',
            unique_together={('cart', 'book')},
        ),
    ]
