# Generated by Django 3.0.7 on 2020-07-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20200723_1835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktocart',
            unique_together=set(),
        ),
    ]
