# Generated by Django 3.0.7 on 2020-07-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0073_auto_20200724_1239'),
        ('cart', '0018_auto_20200724_1313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktocart',
            unique_together={('cart', 'book')},
        ),
    ]
