# Generated by Django 3.0.7 on 2020-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20200618_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(upload_to='series', verbose_name='Изображение'),
        ),
    ]
