# Generated by Django 3.0.7 on 2020-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20200701_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(null=True, upload_to='series', verbose_name='Изображение'),
        ),
    ]
