# Generated by Django 3.0.7 on 2020-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_import_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='series/notfound_0.png', upload_to='series', verbose_name='Изображение'),
        ),
    ]
