# Generated by Django 3.0.7 on 2020-06-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200615_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
    ]
