# Generated by Django 3.0.7 on 2020-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(verbose_name='Год рождения'),
        ),
    ]
