# Generated by Django 3.0.7 on 2020-06-16 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_auto_20200615_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
