# Generated by Django 3.0.7 on 2020-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_auto_20200616_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors', verbose_name='Изображение'),
        ),
    ]
