# Generated by Django 3.0.7 on 2020-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_auto_20200616_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='media/authors/incognito.png', upload_to='authors', verbose_name='Изображение'),
        ),
    ]
