# Generated by Django 3.0.7 on 2020-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_auto_20200616_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='authors', verbose_name='Изображение'),
        ),
    ]
