# Generated by Django 3.0.7 on 2020-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_auto_20200616_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
