# Generated by Django 3.0.7 on 2020-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0011_auto_20200617_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(help_text='Дата должна быть в формате ДД.ММ.ГГГГ', verbose_name='Дата рождения'),
        ),
    ]
