# Generated by Django 3.0.7 on 2020-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0015_auto_20200627_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(help_text='ДД.ММ.ГГГГ', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='authors', verbose_name='Изображение'),
        ),
    ]
