# Generated by Django 3.0.7 on 2020-07-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0016_auto_20200711_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors', verbose_name='Изображение'),
        ),
    ]
