# Generated by Django 3.0.7 on 2020-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_import_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.ImageField(default='publishers/notfound_0.png', upload_to='publishers', verbose_name='Изображение'),
        ),
    ]
