# Generated by Django 3.0.7 on 2020-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_auto_20200717_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Поле может быть пустым', null=True, verbose_name='Краткая информация об издательстве'),
        ),
    ]
