# Generated by Django 3.0.6 on 2020-06-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.FileField(upload_to='apache_logs/apache_logs.txt', verbose_name='Лог')),
            ],
        ),
        migrations.AlterField(
            model_name='brousers',
            name='brousers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser_apache.Row_line', verbose_name='Соответствующая строка'),
        ),
        migrations.AlterField(
            model_name='row_line',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='time_from_log',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser_apache.Row_line', verbose_name='Соответствующая строка'),
        ),
    ]
