# Generated by Django 3.0.6 on 2020-06-02 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0002_auto_20200602_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='log',
        ),
        migrations.AddField(
            model_name='log',
            name='db_log',
            field=models.FileField(default=django.utils.timezone.now, upload_to='apache_logs/apache_logs_small.txt'),
            preserve_default=False,
        ),
    ]
