# Generated by Django 3.0.6 on 2020-06-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0004_auto_20200602_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='time',
        ),
    ]
