# Generated by Django 3.0.6 on 2020-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0005_remove_parser_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='brouser',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Браузеры'),
        ),
    ]
