# Generated by Django 3.0.6 on 2020-06-02 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0007_auto_20200602_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parser',
            name='brouser',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Браузеры'),
        ),
    ]
