# Generated by Django 3.0.6 on 2020-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0009_auto_20200602_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='time',
            field=models.DateTimeField(verbose_name='Дата и время запроса'),
        ),
    ]
