# Generated by Django 3.0.6 on 2020-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0010_auto_20200602_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='brouser',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Браузеры'),
        ),
    ]
