# Generated by Django 3.0.6 on 2020-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0011_auto_20200602_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='bot',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Боты и поисковые системы'),
        ),
    ]
