# Generated by Django 3.0.6 on 2020-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0013_auto_20200602_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='protocol',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Протокол'),
        ),
    ]
