# Generated by Django 3.0.6 on 2020-06-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0014_parser_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='protocol',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Протокол'),
        ),
    ]
