# Generated by Django 3.0.6 on 2020-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0015_auto_20200602_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='referer',
            field=models.TextField(blank=True, null=True, verbose_name='URL-запроса'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='bot',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='brouser',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='protocol',
            field=models.TextField(blank=True, null=True, verbose_name='Протокол'),
        ),
    ]
