# Generated by Django 3.0.6 on 2020-06-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0016_auto_20200603_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='system',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Информация о системе'),
        ),
    ]
