# Generated by Django 3.0.6 on 2020-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0018_auto_20200603_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='referer',
            field=models.URLField(blank=True, null=True, verbose_name='URL-запроса'),
        ),
    ]
