# Generated by Django 3.0.6 on 2020-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0020_auto_20200603_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='ip',
            field=models.GenericIPAddressField(default='192.0.2.1', verbose_name='IP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parser',
            name='byte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во отправленных байтов клиенту'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Статус ответа сервера'),
        ),
    ]
