# Generated by Django 3.0.6 on 2020-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0021_auto_20200603_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brousers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brouser', models.CharField(max_length=300, verbose_name='Браузеры')),
                ('user_agents', models.TextField(blank=True, null=True, verbose_name='Соответствующие user_agents')),
            ],
        ),
    ]
