# Generated by Django 3.0.6 on 2020-06-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0022_brousers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brousers',
            new_name='Brouser',
        ),
    ]
