# Generated by Django 3.0.6 on 2020-06-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0023_auto_20200603_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brouser',
            name='user_agents',
            field=models.TextField(blank=True, null=True, verbose_name='Соответ. user_agents'),
        ),
    ]
