# Generated by Django 3.0.6 on 2020-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0024_auto_20200603_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bots', models.CharField(max_length=300, verbose_name='Бот/поисковая система')),
                ('user_agents', models.TextField(blank=True, null=True, verbose_name='Соответ. user_agents')),
            ],
        ),
    ]
