# Generated by Django 3.0.6 on 2020-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0025_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='user_agents',
            field=models.URLField(blank=True, null=True, verbose_name='Соответ. user_agents'),
        ),
    ]
