# Generated by Django 3.0.6 on 2020-06-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0027_auto_20200603_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-bots']},
        ),
    ]
