# Generated by Django 3.0.6 on 2020-06-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0029_auto_20200603_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='brouser',
            field=models.CharField(blank=True, help_text='Поле браузера', max_length=300, null=True, verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP запроса', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='log',
            field=models.TextField(help_text='Лог файла Apache', verbose_name='Лог'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='system',
            field=models.TextField(blank=True, help_text='Информация о системе пользователя', null=True, verbose_name='Информация о системе'),
        ),
    ]
