# Generated by Django 3.0.6 on 2020-06-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0030_auto_20200603_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='brouser',
        ),
    ]
