# Generated by Django 3.0.6 on 2020-06-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0031_auto_20200604_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='brou',
            field=models.ForeignKey(blank=True, help_text='Поле браузера, с которого был сделан запрос', null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_apache.Brouser', verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='bо',
            field=models.ForeignKey(blank=True, help_text='Название бота/поисковой системы, который сделали запрос', null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_apache.Bot', verbose_name='Бот'),
        ),
    ]
