# Generated by Django 3.0.6 on 2020-06-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_apache', '0032_auto_20200604_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='brou',
            field=models.ForeignKey(blank=True, help_text='Поле браузера, с которого был сделан запрос (может быть пустым)', null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_apache.Brouser', verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='byte',
            field=models.IntegerField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Кол-во отправленных байтов клиенту'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='bо',
            field=models.ForeignKey(blank=True, help_text='Название бота/поисковой системы, который сделали запрос (может быть пустым)', null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_apache.Bot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='protocol',
            field=models.TextField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='referer',
            field=models.URLField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='URL-запроса'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='status',
            field=models.IntegerField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Статус ответа сервера'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='system',
            field=models.TextField(blank=True, help_text='Информация о системе пользователя (может быть пустым)', null=True, verbose_name='Информация о системе'),
        ),
    ]
